name: Building Fires
favicon: null
layout_spectrum: 0.9547059158794582
typography_spectrum: 0.33419340616092086
title: Building Fires
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-6498445-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5774401747621596
  lightness: 0.3054740163497627
  saturation: 0.7054013293236494
  rhythmicContrast: 0.420072432840243
purpose: []
