name: Building Fires
favicon: null
layout_spectrum: 0.91596
typography_spectrum: 0.12914
title: Building Fires
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75661672-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f19a9c'
    - '#feeeb5'
    - '#000100'
    - '#f8c8ab'
    - '#744847'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
